// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChRJrSqwEQc0MuahBR5nQWl_UxUjoN7dE',
    appId: '1:98672363014:web:d521eed2b49f3d4aea2587',
    messagingSenderId: '98672363014',
    projectId: 'categorias-10f78',
    authDomain: 'categorias-10f78.firebaseapp.com',
    storageBucket: 'categorias-10f78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcBYuzfrLdTVn_akxMpJkrrGeG8JRqDZE',
    appId: '1:98672363014:android:7a5fab9b5f4f5d8dea2587',
    messagingSenderId: '98672363014',
    projectId: 'categorias-10f78',
    storageBucket: 'categorias-10f78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA0cs4-Qu3-6qZWV72qgEKhUOau_4PMrE',
    appId: '1:98672363014:ios:58c2878320b80e91ea2587',
    messagingSenderId: '98672363014',
    projectId: 'categorias-10f78',
    storageBucket: 'categorias-10f78.firebasestorage.app',
    iosBundleId: 'com.espino.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA0cs4-Qu3-6qZWV72qgEKhUOau_4PMrE',
    appId: '1:98672363014:ios:58c2878320b80e91ea2587',
    messagingSenderId: '98672363014',
    projectId: 'categorias-10f78',
    storageBucket: 'categorias-10f78.firebasestorage.app',
    iosBundleId: 'com.espino.app',
  );
}
